spring.boot:
  admin:
    url: http://localhost:9095
    client:
      name: customer-service

spring.redis:
  host: 192.168.1.60
  port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info  # Expose only health and info endpoints

spring:
  application.name: customer-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.1.60:3307/customer?allowPublicKeyRetrieval=true&useSSL=false
  password: root1234
  username: root

spring.jackson:
  property-naming-strategy: SNAKE_CASE

spring. jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop




spring.main:
  allow-bean-definition-overriding: true


