spring.boot:
  admin:
    client:
      url: http://192.168.1.60:9095
      name: customer-service

spring.redis:
  host: 192.168.1.60
  port: 6379

management:
  endpoints:
    web:
      base-path: /customer/actuator
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans,env, beans, caches, configprops, loggers, httptrace, mappings, shutdown, threaddump, conditions

spring:
  application.name: customer-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.1.60:3307/customer?allowPublicKeyRetrieval=true&useSSL=false
  password: root1234
  username: root

spring.jackson:
  property-naming-strategy: SNAKE_CASE

spring. jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop




spring.main:
  allow-bean-definition-overriding: true


