spring:
  application.name: customer-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/customer?useSSL=false
      password: root1234
      username: root

spring.jackson:
        property-naming-strategy: SNAKE_CASE

spring. jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop

spring.main:
    allow-bean-definition-overriding: true

spring.server.port: 8085
