server:
  port: 8085


spring.boot:
  admin:
    client:
      url: http://192.168.1.60:9095
      name: product-service


management:
  info:
    env.enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans,env, beans, caches, configprops, loggers, httptrace, mappings, shutdown, threaddump, conditions


spring.data.mongodb.uri: mongodb://192.168.1.60:27017/product

#  mongodb+srv://Cluster70289:c1RsZ0x0XlVa@cluster70289.pl9p3ua.mongodb.net/products?retryWrites=true&w=majority
spring.kafka:
    topic: "product-events"
    producer:
      bootstrap-servers: 192.168.1.60:19092,192.168.1.60:29092,192.168.1.60:39092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: 192.168.1.60:19092,192.168.1.60:29092,192.168.1.60:39092

spring:
  application.name: product-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/customer?useSSL=false
      password: root1234
      username: root

spring.jackson:
        property-naming-strategy: SNAKE_CASE

spring. jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop

spring.main:
    allow-bean-definition-overriding: true


