apiVersion: v1
kind: Service
metadata:
  name: customer-service-lb
  namespace: ecommerce
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort