apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: ecommerce
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8089
  type: NodePort